language: haskell
ghc:
  - 7.8

install:
    - cabal install text
    - cabal install mtl-2.1.3.1
    - cabal install cabal cabal-install
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests
    - cabal build
    - cabal install
    - cabal test --show-details=always

after_success:
    - make -i hlint

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false
