language: haskell
ghc:
  - 7.8

env:
    - GHC_PATH=/opt/ghc/7.10.2/bin
    - GHC_PATH="" # default ghc specified above

before_install:
    - ls /opt/ghc/
    - ls /usr/local/ghc/
    - PATH=/opt/cabal/1.22/bin:$PATH
    - if [ -z $GHC_PATH ]; then :; else PATH=$GHC_PATH:$PATH; fi
    - env
    - cabal --version
    - ghc --version

install:
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure
    - cabal build
    - cabal install
    - cabal configure --enable-tests
    - cabal test --show-details=always

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - socat
      - time
      - ghc-7.10.2
      - cabal-install-1.22 # newer GHCs fail with old cabal
