language: haskell
ghc:
  - 7.10
  - 8.0
  - 8.2
cabal: 1.24

env:
    - CC=gcc-4.0 CXX=g++-4.0

before_install:
    - env
    - cabal --version
    - ghc --version
    - $CXX --version

install:
    - make configure

script:
    - make build
    - make test

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false

addons:
  apt:
    sources:
      - buntu-toolchain-r-test
      - hvr-ghc
    packages:
      - socat
      - time
      - g++-6
      - ghc-8.2
