language: haskell
ghc:
  - 7.8

install:
    - cabal install text
    - cabal install mtl-2.1.3.1
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests
    - cabal build
    - cabal install
    - cabal test --show-details=always || { env; false; }

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: always # default: change
    on_failure: always # default: always

sudo: false
