language: haskell
ghc:
  - 7.8
  - 7.6
  - 7.4

script:
  - cabal install && cabal configure --enable-tests && cabal build && cabal test --show-details=always

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: always # default: change
    on_failure: always # default: always
