language: haskell
ghc:
  - 7.10
  - 8.0
  - 8.2

before_install:
    - env
    - cabal --version
    - ghc --version

install:
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure
    - cabal build
    - cabal install
    - cabal configure --enable-tests
    - cabal test --show-details=always

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false

addons:
  apt:
    packages:
      - socat
      - time
