language: generic
sudo: false

cache:
  directories:
    - $HOME/.stack

matrix:
  include:
    - env: GHC=ghc-8.4 CC=gcc-7 CXX=g++-7
    - env: GHC=ghc-8.2 CC=gcc-7 CXX=g++-7

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - env
    - stack --compiler ${GHC} exec ghc --version
    - $CXX --version

install:
    - true

script:
    - stack --compiler ${GHC} exec make build
    - stack --compiler ${GHC} exec make test

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - socat
      - time
      - g++-7
      - libgmp-dev # for the sake of Haskell stack
      - acl
      - libacl1-dev
