language: haskell
ghc:
  - 7.8

install:
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure
    - cabal build
    - cabal install
    - cabal configure --enable-tests
    - cabal test --show-details=always

after_success:
    - cabal install hlint
    - make -i hlint

notifications:
  email:
    recipients:
      - xstill@fi.muni.cz
    on_success: change # default: change
    on_failure: always # default: always

sudo: false
