resolver:  lts-11.15
allow-newer: true
packages:
- src/hs
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: [ printf-mauke-0.7.0 ]

# Override default flag values for local packages and extra-deps
flags:

# Control whether we use the GHC we find on the path
# system-ghc: true
